[package]
name = "factorio-config"
version = "0.1.0"
edition = "2021"

[dependencies]
nutype = { version = "0.4.0", features = ["serde"] }
serde = { version = "1.0.197", features = ["derive"] }

[dev-dependencies]
serde_json = "1.0.114"
