name: Release

on:
  workflow_dispatch:
  release:
    types:
      - published
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Setup local .NET tools
      run: dotnet tool restore
    - name: Setup dotnet-deb tool
      run: dotnet tool run dotnet-deb install
    - name: Create debian package
      run: dotnet tool run dotnet-deb -c Release src/Factoriod.Daemon/Factoriod.Daemon.csproj
    - name: Configure GPG Key
      run: |
        echo -n "$GPG_SIGNING_KEY" | base64 --decode | gpg --import
      env:
        GPG_SIGNING_KEY: ${{ secrets.GPG_SIGNING_KEY }}
    - uses: actions/upload-artifact@v3
      with:
        name: factoriod-deb
        path: src/Factoriod.Daemon/bin/Release/net6.0/factoriod.*.deb
