name: Release


on:
  workflow_dispatch:
  release:
    types:
      - published
    
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Create release assets
      run: dotnet publish -c Release --sc -r linux-x64 -p:PublishSingleFile=true -p:PublishReadyToRun=true -p:IncludeNativeLibrariesForSelfExtract=true
    - name: Rename executable
      run: mkdir dist && cp ./src/Factoriod.Fetcher/bin/Release/net6.0/linux-x64/publish/Factoriod.Fetcher ./dist/factorio-fetcher
    - uses: actions/upload-artifact@v3
      with:
        name: fetcher-executable
        path: dist/factorio-fetcher
  release:
    runs-on: ubuntu-latest
    needs:
      - build
    if: startsWith(github.ref, 'refs/tags/')
    steps:
    - uses: actions/download-artifact@v3
      with:
        name: fetcher-executable
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: fetcher-executable
